#!/bin/sh

prefix="/usr"
exec_prefix="${prefix}"
xrdb="xrdb"
xinitdir="/etc/X11/xinit"
xclock="xclock"
xterm="xterm"
twm="twm"
xmodmap="xmodmap"

userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
sysresources="$xinitdir/.Xresources"
sysmodmap="$xinitdir/.Xmodmap"

# merge in defaults and keymaps

if [ -f "$sysresources" ]; then
    if [ -x /usr/bin/cpp ] ; then
        "$xrdb" -merge "$sysresources"
    else
        "$xrdb" -nocpp -merge "$sysresources"
    fi
fi

if [ -f "$sysmodmap" ]; then
    "$xmodmap" "$sysmodmap"
fi

if [ -f "$userresources" ]; then
    if [ -x /usr/bin/cpp ] ; then
        "$xrdb" -merge "$userresources"
    else
        "$xrdb" -nocpp -merge "$userresources"
    fi
fi

if [ -f "$usermodmap" ]; then
    "$xmodmap" "$usermodmap"
fi

# start some nice programs

if [ -d "$xinitdir"/xinitrc.d ] ; then
	for f in "$xinitdir/xinitrc.d"/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# "$twm" &
# "$xclock" -geometry 50x50-1+1 &
# "$xterm" -geometry 80x50+494+51 &
# "$xterm" -geometry 80x20+494-0 &
# exec "$xterm" -geometry 80x66+0+0 -name login
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources" &
xrdbpid=$!

autostart="picom mpd pipewire unclutter dunst"

for program in $autostart; do
	[ -n "$(pgrep "$program")" ] || "$program" &
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"

# load color profile
xcalib -d "$DISPLAY" /usr/share/color/icc/BOE_CQ_______NE135FBM_N41_03.icm >/dev/null 2>&1

screenconf
redunst

# Activate dbus variable
dbus-update-activation-environment --all
dbus-launch ssh-agent dwm
exec dwm >~/.dwm.log 2>&1
# startx -- -keeptty >~/.xorg.log 2>&1
