#!/bin/sh


xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources" &
xrdbpid=$!

autostart="picom mpd pipewire remapd unclutter"

for program in $autostart; do
	[ -n "$(pgrep "$program")" ] || "$program" &
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"
screenconf

[ -n "$(pgrep dunst)" ] || dunst &
