#! /bin/sh

# DavesGarage
https://www.youtube.com/channel/UCNzszbnvQeFzObW0ghk0Ckw
# steve_seguin
https://www.youtube.com/channel/UCMc1GFSONeLSKvXuHx_N51a
# chris@machine
https://www.youtube.com/channel/UCS97tchJDq17Qms3cux8wcA
# TjDeVries
https://www.youtube.com/channel/UCd3dNckv1Za2coSaHGHl5aA
# Vulf
https://www.youtube.com/channel/UCtWuB1D_E3mcyYThA9iKggQ
# ThePrimeagen
https://www.youtube.com/channel/UC8ENHE5xdFSwx71u3fDH5Xw
# gotbletu
https://www.youtube.com/channel/UCkf4VIqu3Acnfzuk3kRIFwA
# DistroTube
https://www.youtube.com/channel/UCVls1GmFKf6WlTraIb_IaJg
# EngineerMan
https://www.youtube.com/channel/UCrUL8K81R4VBzm-KOYwrcxQ
# CyberGizmo
https://www.youtube.com/channel/UC05XpvbHZUQOfA6xk4dlmcw
# ChrisTitusTech
https://www.youtube.com/channel/UCg6gPGh8HU2U01vaFCAsvmQ
# The Linux Experiment
https://www.youtube.com/channel/UC5UAwBUum7CPN5buc-_N1Fw
# Stephanie Boyer
#https://www.youtube.com/channel/UCqEhy3CPZ4J1GaZXBgtH1w
# Alloprof
#https://www.youtube.com/channel/UCipxMKDpPocgPiXzPFUsrgg
# freecodecamp
https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ
# bugswriter_
https://www.youtube.com/channel/UCngn7SVujlvskHRvRKc1cTw
# TheLinuxCast
https://www.youtube.com/channel/UCylGUf9BvQooEFjgdNudoQg
# LinusTechTips
https://www.youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw
# hackfestca
https://www.youtube.com/channel/UCSckp-N4zP4V8GnZGxVqjTg
# SousEcoute
https://www.youtube.com/channel/UCKhVag9OGIOJu_x430Dmedw
# cbtnuggets
https://www.youtube.com/channel/UClIFqsmxnwVNNlsvjH1D1Aw
# LukeSmithxyz
https://www.youtube.com/channel/UC2eYFnH61tmytImy1mTYvhA
# RoboNuggie
https://www.youtube.com/channel/UCxwcmRAmBRzZMNS37dCgmHA
# KalosLikesComputers
https://www.youtube.com/channel/UCSsHJShN9qNXqXD1j2emaqg
# t3dotgg
https://www.youtube.com/channel/UCbRP3c757lWg9M-U7TyEkXA
# MelkeyDev
https://www.youtube.com/channel/UC1Zfv1Zrp1q5lKgBomzOyCA
# steve_seguin
https://www.youtube.com/channel/UCMc1GFSONeLSKvXuHx_N51A
# RadioCanadaInfo
https://www.youtube.com/channel/UClxaaAzHu1B5EoTtBYea7ig
# Radpointca
https://www.youtube.com/channel/UCVBA7-PfzHIkfPfZ3UiqWdg
# RadioCanada
https://www.youtube.com/channel/UCi8BnqbhQripV0V-gqx7oEg
# RTINGSdotcom
https://www.youtube.com/channel/UCAi6GKtTPoYxUheIbVhnwqw
# TechnoTim
https://www.youtube.com/channel/UCOk-gHyjcWZNj3Br4oxwh0A
# Level1Techs
https://www.youtube.com/channel/UC4w1YQAJMWOz4qtxinq55LQ
# Pomplamoose
https://www.youtube.com/channel/UCSiPjfAJBgbFlIUsxOWpK0w
# ScaryPockets
https://www.youtube.com/channel/UC-2JUs_G21BrJ0efehwGkUw
# Le_Mef
https://www.youtube.com/channel/UCJs0hk9Ib9stBmiBdvG2zkQ
# BadFriends
https://www.youtube.com/channel/UCRBpynZV0b7ww2XMCfC17qg
# davidbombal
https://www.youtube.com/channel/UCP7WmQ_U4GB3K51Od9QvM0w
# Nerdslesson
https://www.youtube.com/channel/UCyFWoLmPTgZ3BkHIKMRSV1g
# SmallBrainedAmerican
https://www.youtube.com/channel/UCHASrbCS-niYRn-Y3WX38pA
# markets
https://www.youtube.com/channel/UCIALMKvObZNtJ6AmdCLP7Lg
# programmersarealsohuman5909
https://www.youtube.com/channel/UCi8C7TNs2ohrc6hnRQ5Sn2w
# BroCodez
https://www.youtube.com/channel/UC4SVo0Ue36XCfOyb5Lh1viQ
# tva_nouvelles
https://www.youtube.com/channel/UCgKzdfWnTie2OD4bfaZKaQw
# BandTheLiquorStore
https://www.youtube.com/channel/UCvISIg_p5A19MzavYSojNyw
# CBCNews
https://www.youtube.com/channel/UCuFFtHWoLl5fauMMD5Ww2jA
# omalleyrock
https://www.youtube.com/channel/UCDIJ45Bba6nzrGL5v8b7fMw
# LiveOverflow
https://www.youtube.com/channel/UClcE-kVhqyiHCcjYwcpfj9w
# NovaspiritTech
https://www.youtube.com/channel/UCrjKdwxaQMSV_NDywgKXVmw
# JeffGeerling
https://www.youtube.com/channel/UCR-DXc1voovS8nhAvccRZhg
# NetworkChuck
https://www.youtube.com/channel/UC9x0AN7BWHpCDHSm9NiJFJQ
# TheMobReporter
https://www.youtube.com/channel/UCnsj4TU7mOQ-4l2HOaRekgA
# TonyTeachesTech
https://www.youtube.com/channel/UCWPJwoVXJhv0-ucr3pUs1dA
# VICE-TV
https://www.youtube.com/channel/UCWF0PiUvUi3Jma2oFgaiX2w
# MTV
https://www.youtube.com/channel/UCxAICW_LdkfFYwTqTHHE0vg
# FrameworkComputer
https://www.youtube.com/channel/UCDiKw3GnFIwyNJBzhCoRI-Q
# lexfridman
https://www.youtube.com/channel/UCSHZKyawb77ixDdsGog4iWA
# Atomicmarvel
https://www.youtube.com/channel/UC1xaOCNeVbO9q9cnoCA-XaA
# theHacksmith
https://www.youtube.com/channel/UCjgpFI5dU-D1-kh9H1muoxQ
# MrVolt
https://www.youtube.com/channel/UCvOOv9tfBMSzcXnDkgzMufA
# kexp
https://www.youtube.com/channel/UC3I2GFN_F8WudD_2jUZbojA
# TallPaulTech
https://www.youtube.com/channel/UCcmw3P6BDUFA4h3Y_FpsB_w
# @ImZipux

# ImZipux
https://www.youtube.com/channel/UCoS8kP28lY4mkjOt5Znv9LA
# MashedLinux
https://www.youtube.com/channel/UC-V8FVQCUpRRUPNClviki3w
# TsodingDaily
https://www.youtube.com/channel/
# limperatrice_
https://www.youtube.com/channel/UCogofxZDDXkpKf0S8MnxLMQ
# AndrewGiraffe
https://www.youtube.com/channel/
