#!/bin/sh
#
# AUTHOR: cf.
#
# DATE: 2024-07-19
#
# DESC: Elvi to search Manned
# elvis: manned		-- Search Manned (www.manned.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Manned (www.manned.org) for man pages
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.manned.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.manned.org/man/${escaped_args}"
fi
